---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-spring-app-4-testing-debugging-in-k8s.fullname" . }}
  labels:
    {{- include "simple-spring-app-4-testing-debugging-in-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: service8088
      port: {{ .Values.service.port }}
      targetPort: http8088
      protocol: TCP
  selector:
    {{- include "simple-spring-app-4-testing-debugging-in-k8s.selectorLabels" . | nindent 4 }}
