name: Test environment

on:
  push:
    branches:
      - main

env:
  JAVA_IMAGE_NAME: 'simple-app'
  JAVA_DOCKERFILE_TARGET: 'simple_app'

jobs:
  docker:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
      issues: write
    steps:
      # —— Setup Environment actions  ——————————————————————————————————————————————

      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

      -   name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      # —— Build latest image  —————————————————————————————————————————————————————

      -   name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            target: ${{ env.JAVA_DOCKERFILE_TARGET }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: |
              ghcr.io/rieicp/${{ env.JAVA_IMAGE_NAME }}:v1.1.0
